syntax = "proto3";

package adlerhurst.cli.v1alpha;

option go_package = "github.com/adlerhurst/cli-client;cli";

import "google/protobuf/descriptor.proto";

// if defined the generated code includes a main
// function to compile the code with any further interaction
extend google.protobuf.FileOptions {
    CLIOption cli = 51000;
}

message CLIOption {
    string name = 1;
}

// defines the commands name
// e.g. ./my-cli user
// my-cli ${service.command_name}
extend google.protobuf.ServiceOptions {
    ServiceCommand command = 51000;
}

message ServiceCommand {
    message SubCommand{
        string name = 1;
        optional string short_description = 2;
        optional string long_description = 3;
        repeated SubCommand sub_commands = 4;
    }

    string name = 1;
    optional bool ignored = 2;
    repeated SubCommand sub_commands = 3;
}

// defines the subcommands name
// e.g. ./my-cli user add
// my-cli ${service.command_name} ${method.name}
extend google.protobuf.MethodOptions {
    MethodCommand sub_command = 51000;
}

message MethodCommand {
    message ParentCommand {
        string name = 1;
    }
    string name = 1;
    optional bool ignored = 2;
    // by default the command of the service is taken
    // only defined sub commands of the service are allowed
    optional ParentCommand parent = 3;
}

// my-cli ${service.command_name} ${method.name} --${field.arg_name}
extend google.protobuf.FieldOptions {
    FlagOption flag = 51000;
}

message FlagOption {
    string name = 1;
    bool ignored = 2;
}