// Code generated by protoc-gen-cli-client. DO NOT EDIT.

package cli

import (
	cli_client "github.com/adlerhurst/cli-client"
	"github.com/spf13/pflag"
)



var _ cli_client.FlagSet = (*CallRequest)(nil)
var _ cli_client.FlagSet = (*CallRequest_Nested)(nil)

func (msg *CallRequest) PrimitiveValues()[]cli_client.PrimitiveValue {
	return []cli_client.PrimitiveValue{
		 cli_client.NewValue(
			&msg.UseFieldName, 
			cli_client.FlagInfo{
				Name: "UseFieldName",
				Shorthand: "",
				Usage: "",
			},
		),
		 cli_client.NewValue(
			&msg.UseCustomName, 
			cli_client.FlagInfo{
				Name: "UseCustomName",
				Shorthand: "",
				Usage: "",
			},
		),
		 cli_client.NewValue(
			&msg.Wat, 
			cli_client.FlagInfo{
				Name: "Wat",
				Shorthand: "",
				Usage: "",
			},
		),
		 cli_client.NewValue(
			&msg.IsSomething, 
			cli_client.FlagInfo{
				Name: "IsSomething",
				Shorthand: "",
				Usage: "",
			},
		),
		 cli_client.NewValue(
			&msg.Ui32, 
			cli_client.FlagInfo{
				Name: "Ui32",
				Shorthand: "",
				Usage: "",
			},
		),
		 cli_client.NewValue(
			&msg.I64, 
			cli_client.FlagInfo{
				Name: "I64",
				Shorthand: "",
				Usage: "",
			},
		),
		 cli_client.NewValue(
			&msg.Ui64, 
			cli_client.FlagInfo{
				Name: "Ui64",
				Shorthand: "",
				Usage: "",
			},
		),
		 cli_client.NewValue(
			&msg.Fl, 
			cli_client.FlagInfo{
				Name: "Fl",
				Shorthand: "",
				Usage: "",
			},
		),
		 cli_client.NewValue(
			&msg.Dbl, 
			cli_client.FlagInfo{
				Name: "Dbl",
				Shorthand: "",
				Usage: "",
			},
		),
		 cli_client.NewValue(
			&msg.Beiz, 
			cli_client.FlagInfo{
				Name: "Beiz",
				Shorthand: "",
				Usage: "",
			},
		),
		 cli_client.NewValue(
			&msg.Si32, 
			cli_client.FlagInfo{
				Name: "Si32",
				Shorthand: "",
				Usage: "",
			},
		),
		 cli_client.NewValue(
			&msg.Si64, 
			cli_client.FlagInfo{
				Name: "Si64",
				Shorthand: "",
				Usage: "",
			},
		),
		 cli_client.NewValue(
			&msg.F32, 
			cli_client.FlagInfo{
				Name: "F32",
				Shorthand: "",
				Usage: "",
			},
		),
		 cli_client.NewValue(
			&msg.F64, 
			cli_client.FlagInfo{
				Name: "F64",
				Shorthand: "",
				Usage: "",
			},
		),
		 cli_client.NewValue(
			&msg.Sf32, 
			cli_client.FlagInfo{
				Name: "Sf32",
				Shorthand: "",
				Usage: "",
			},
		),
		 cli_client.NewValue(
			&msg.Sf64, 
			cli_client.FlagInfo{
				Name: "Sf64",
				Shorthand: "",
				Usage: "",
			},
		),
		 cli_client.NewValue(
			&msg.Some, 
			cli_client.FlagInfo{
				Name: "Some",
				Shorthand: "",
				Usage: "",
			},
		),
		 cli_client.NewSliceValue(
			&msg.RepS,
			cli_client.FlagInfo{
				Name: "RepS",
				Shorthand: "",
				Usage: "",
			},
		),
		 cli_client.NewSliceValue(
			&msg.RepWat,
			cli_client.FlagInfo{
				Name: "RepWat",
				Shorthand: "",
				Usage: "",
			},
			),
	}
	// // Nested
	// _NestedFlags := pflag.NewFlagSet("Nested", pflag.ContinueOnError)
	// msg.Nested.SetFlags(_NestedFlags)
	// // CreatedAt
	// _CreatedAtFlags := pflag.NewFlagSet("CreatedAt", pflag.ContinueOnError)
	// msg.CreatedAt.SetFlags(_CreatedAtFlags)
	// // Payload
	// _PayloadFlags := pflag.NewFlagSet("Payload", pflag.ContinueOnError)
	// msg.Payload.SetFlags(_PayloadFlags)
	// // Something
	// _SomethingFlags := pflag.NewFlagSet("Something", pflag.ContinueOnError)
	// msg.Something.SetFlags(_SomethingFlags)
}


func (msg *CallRequest) NestedValues() map[string]cli_client.FlagSet{
	return map[string]cli_client.FlagSet{
		"Nested": msg.Nested,
	}
}

func (msg *CallRequest) parseNestedFlags(args []string) error{
	msg.Nested = new(CallRequest_Nested)
	set := pflag.NewFlagSet("Nested", pflag.ContinueOnError)
	for _, value := range msg.Nested.PrimitiveValues() {
		value.Add(set)
	}
	return set.Parse(args)
}

func (msg *CallRequest_Nested) PrimitiveValues() []cli_client.PrimitiveValue{
	return nil
}

func (msg *CallRequest_Nested) NestedValues() map[string]cli_client.FlagSet{
	return nil
}

// func (msg *NestedRequest_Nested) SetFlags(set *pflag.FlagSet) {
// 	cli_client.NewValue(&msg.Id).Add(set, "Id", "", "")
// 	cli_client.NewValue(&msg.Depth).Add(set, "Depth", "", "")
// }

// func (msg *NestedRequest) SetFlags(set *pflag.FlagSet) {
// 	cli_client.NewValue(&msg.Id).Add(set, "Id", "", "")
// 	// Nested
// 	_NestedFlags := pflag.NewFlagSet("Nested", pflag.ContinueOnError)
// 	msg.Nested.SetFlags(_NestedFlags)
// }

// func (msg *ServerSideStreamRequest) SetFlags(set *pflag.FlagSet) {
// 	cli_client.NewValue(&msg.Text).Add(set, "Text", "", "")
// }

// func (msg *ClientSideStreamRequest) SetFlags(set *pflag.FlagSet) {
// 	cli_client.NewValue(&msg.Text).Add(set, "Text", "", "")
// }

// func (msg *BidirectionalStreamRequest) SetFlags(set *pflag.FlagSet) {
// 	cli_client.NewValue(&msg.Text).Add(set, "Text", "", "")
// }
