// Code generated by protoc-gen-cli-client. DO NOT EDIT.

package cli

import (
	cli_client "github.com/adlerhurst/cli-client"
	pflag "github.com/spf13/pflag"
	"google.golang.org/protobuf/types/known/anypb"
	"google.golang.org/protobuf/types/known/structpb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

func (msg *CallRequest) PrimitiveFlags()[]string{
	return []string{
		"UseFieldName",
		"UseCustomName",
		"Wat",
		"IsSomething",
		"Ui32",
		"I64",
		"Ui64",
		"Fl",
		"Dbl",
		"Beiz",
		"Si32",
		"Si64",
		"F32",
		"F64",
		"Sf32",
		"Sf64",
		"Some",
		"RepS",
		"RepWat",
	}
}

func (msg *CallRequest) NestedFlag(flagName string) cli_client.Flagger{
	switch flagName{
	case "Nested":
		if msg.Nested == nil{
			msg.Nested = new(CallRequest_Nested)
		}
		return msg.Nested
	case "CreatedAt":
		return msg.CreatedAt
	case "Payload":
		return msg.Payload
	case "Something":
		return msg.Something
	}
	return nil
}

func (msg *CallRequest_Nested) PrimitiveFlags() []string{
	return []string{
		"Field",
	}
}

type assignedFlags struct{
	set *pflag.FlagSet
	args []string
}

// flag name is primitive
var callRequestNestedFlags = map[string]func(msg *CallRequest,args []string)error{
	"Nested": func(msg *CallRequest, args []string)error{
		msg.Nested = new(CallRequest_Nested)
		return msg.Nested.ParseFlags(args)
	},
	"CreatedAt": func(msg *CallRequest, args []string)error{
		msg.CreatedAt = new(timestamppb.Timestamp)
		return msg.CreatedAt.ParseFlags(args)
	},
	"Payload": func(msg *CallRequest, args []string)error{
		msg.Payload = new(structpb.Struct)
		return msg.Payload.ParseFlags(args)
	},
	"Something": func(msg *CallRequest, args []string)error{
		msg.Something = new(anypb.Any)
		return msg.Something.ParseFlags(args)
	},
}

func (msg *CallRequest) AssignIndexes(args []string) []assignedFlags{
	assigned := make([]assignedFlags, 0, len(args)/2)

	// primitives first
	primitiveFlags , args := msg.PrimitivesIndex(args)
	assigned = append(assigned, assignedFlags{pflag.NewFlagSet("CallRequest", pflag.ContinueOnError), primitiveFlags})


	// nested second

	return assigned
}

var CallRequestCustomParsers = map[string]func(msg *CallRequest, info cli_client.FlagInfo)func(*pflag.FlagSet){
	"CreatedAt": func(msg *CallRequest, info cli_client.FlagInfo) func(*pflag.FlagSet) {
		return cli_client.NewValue(
			msg.CreatedAt, 
			info, 
			cli_client.WithCustomParserValue[timestamppb.Timestamp](cli_client.ParseTimestamp),
			).Add
	},
	"Payload": func(msg *CallRequest, info cli_client.FlagInfo) func(*pflag.FlagSet) {
		return cli_client.NewValue(
			msg.Payload, 
			info,
			cli_client.WithCustomParserValue[structpb.Struct](cli_client.ParseStruct),
			).Add
	},
	"Something": func(msg *CallRequest, info cli_client.FlagInfo) func(*pflag.FlagSet) {
		return cli_client.NewValue(
			msg.Something, 
			info,
			cli_client.WithCustomParserValue[anypb.Any](cli_client.ParseAny),
			).Add
	},
}

func (msg *CallRequest) ParseFlags(args []string)error {
	*msg = CallRequest{}
	set := pflag.NewFlagSet("CallRequest", pflag.ContinueOnError)

	cli_client.NewValue(&msg.UseFieldName, cli_client.FlagInfo{Name: "UseFieldName"}).Add(set)
	cli_client.NewValue(&msg.UseCustomName, cli_client.FlagInfo{Name: "UseCustomName"}).Add(set)
	cli_client.NewValue(&msg.Wat, cli_client.FlagInfo{Name: "Wat"}).Add(set)
	cli_client.NewValue(&msg.IsSomething, cli_client.FlagInfo{Name: "IsSomething"}).Add(set)
	cli_client.NewValue(&msg.Ui32, cli_client.FlagInfo{Name: "Ui32"}).Add(set)
	cli_client.NewValue(&msg.I64, cli_client.FlagInfo{Name: "I64"}).Add(set)
	cli_client.NewValue(&msg.Ui64, cli_client.FlagInfo{Name: "Ui64"}).Add(set)
	cli_client.NewValue(&msg.Fl, cli_client.FlagInfo{Name: "Fl"}).Add(set)
	cli_client.NewValue(&msg.Dbl, cli_client.FlagInfo{Name: "Dbl"}).Add(set)
	cli_client.NewValue(&msg.Beiz, cli_client.FlagInfo{Name: "Beiz"}).Add(set)
	cli_client.NewValue(&msg.Si32, cli_client.FlagInfo{Name: "Si32"}).Add(set)
	cli_client.NewValue(&msg.Si64, cli_client.FlagInfo{Name: "Si64"}).Add(set)
	cli_client.NewValue(&msg.F32, cli_client.FlagInfo{Name: "F32"}).Add(set)
	cli_client.NewValue(&msg.F64, cli_client.FlagInfo{Name: "F64"}).Add(set)
	cli_client.NewValue(&msg.Sf32, cli_client.FlagInfo{Name: "Sf32"}).Add(set)
	cli_client.NewValue(&msg.Sf64, cli_client.FlagInfo{Name: "Sf64"}).Add(set)
	cli_client.NewValue(&msg.Some, cli_client.FlagInfo{Name: "Some"}).Add(set)
	cli_client.NewSliceValue(&msg.RepS, cli_client.FlagInfo{Name: "RepS"}).Add(set)
	cli_client.NewSliceValue(&msg.RepWat, cli_client.FlagInfo{Name: "RepWat"}).Add(set)

	for flagName, add := range CallRequestCustomParsers{
		delete(callRequestNestedFlags, flagName)
		add(msg, cli_client.FlagInfo{Name: flagName})(set)
	}

	for flagName := range callRequestNestedFlags{
		msg.Nested = new(CallRequest_Nested)
		if err := msg.Nested.ParseFlags(args); err != nil{
			return err
		}
	}

	// primitiveIndex := msg.PrimitivesIndex(args)
	
	// TODO: check if correct increment
	// set.Parse(args[primitiveIndex.from:primitiveIndex.to+1])
	// args = args[primitiveIndex.to+1:]

	// // Nested
	// _NestedFlags := pflag.NewFlagSet("Nested", pflag.ContinueOnError)
	// msg.Nested.SetFlags(_NestedFlags)
	// // CreatedAt
	// _CreatedAtFlags := pflag.NewFlagSet("CreatedAt", pflag.ContinueOnError)
	// msg.CreatedAt.SetFlags(_CreatedAtFlags)
	// // Payload
	// _PayloadFlags := pflag.NewFlagSet("Payload", pflag.ContinueOnError)
	// msg.Payload.SetFlags(_PayloadFlags)
	// // Something
	// _SomethingFlags := pflag.NewFlagSet("Something", pflag.ContinueOnError)
	// msg.Something.SetFlags(_SomethingFlags)
	return nil
}

type index struct{
	from, to int
}

func (msg *CallRequest) PrimitivesIndex(args []string) (flagArgs, remainingArgs[]string){
	for i, arg := range args {
		if arg[0] != '-' {
			continue
		}
		if arg[1] != '-' {
			// TODO: handle shorthand
			continue
		}
		if msg.isPrimitive(arg[2:]) {
			continue
		}
		return args[:i], args[i:]
	}
	return args, nil
}

func (msg *CallRequest) isPrimitive(flagName string) bool{
	switch flagName{
	case "UseFieldName",
		"UseCustomName",
		"Wat",
		"IsSomething",
		"Ui32",
		"I64",
		"Ui64",
		"Fl",
		"Dbl",
		"Beiz",
		"Si32",
		"Si64",
		"F32",
		"F64",
		"Sf32",
		"Sf64",
		"Some",
		"RepS",
		"RepWat":
		return true
	}
	return false
}

func (msg *CallRequest) NestedIndexes(args []string) map[string][][]string {
	indexes := make(map[string][][]string)
	var (
		currentFlag string
	 	currentArgs []string
	)

	for _, arg := range args {
		if arg[0] != '-' {
			currentArgs = append(currentArgs, arg)
			continue
		}
		if arg[1] != '-' {
			// TODO: handle shorthand
			continue
		}
		if !msg.isNested(arg[2:]) {
			continue
		}
		if currentFlag != "" {
			indexes[currentFlag] = append(indexes[currentFlag], currentArgs)
			currentArgs = []string{}
		}
		currentFlag = arg[2:]
		continue
	}
	return indexes
}

func (msg *CallRequest) isNested(flagName string) bool{
	switch flagName{
	case "Nested",
	"CreatedAt",
	"Payload",
	"Something":
		return true
	}
	return false
}

func (msg *NestedRequest_Nested) SetFlags(set *pflag.FlagSet) {
	// cli_client.NewValue(&msg.Id).Add(set, "Id", "", "")
	// cli_client.NewValue(&msg.Depth).Add(set, "Depth", "", "")
}

func (msg *NestedRequest) SetFlags(set *pflag.FlagSet) {
	// cli_client.NewValue(&msg.Id).Add(set, "Id", "", "")
	// // Nested
	// _NestedFlags := pflag.NewFlagSet("Nested", pflag.ContinueOnError)
	// msg.Nested.SetFlags(_NestedFlags)
}

func (msg *ServerSideStreamRequest) SetFlags(set *pflag.FlagSet) {
	// cli_client.NewValue(&msg.Text).Add(set, "Text", "", "")
}

func (msg *ClientSideStreamRequest) SetFlags(set *pflag.FlagSet) {
	// cli_client.NewValue(&msg.Text).Add(set, "Text", "", "")
}

func (msg *BidirectionalStreamRequest) SetFlags(set *pflag.FlagSet) {
	// cli_client.NewValue(&msg.Text).Add(set, "Text", "", "")
}
