// Code generated by protoc-gen-go-cli. DO NOT EDIT.

package cli

import (
	cli_client "github.com/adlerhurst/cli-client"
	cobra "github.com/spf13/cobra"
	pflag "github.com/spf13/pflag"
	os "os"
)

var (
	ExampleCmd = &cobra.Command{
		Use:   "example",
		Short: `This is an example service`,
		Long: `This is an example service
The service does nothing`,
		FParseErrWhitelist: cobra.FParseErrWhitelist{UnknownFlags: true},
		DisableFlagParsing: true,
	}
)
var (
	_ExampleMyCallCmdRequest = &CallRequestFlag{CallRequest: new(CallRequest)}
	ExampleMyCallCmd         = &cobra.Command{
		Use:   "my-call",
		Short: `I do absolutely nothing`,
		Long: `I do absolutely nothing
because i'm a showcase`,
		Run:                runExampleMyCallCmd,
		FParseErrWhitelist: cobra.FParseErrWhitelist{UnknownFlags: true},
		DisableFlagParsing: true,
	}
)

func init() {
	ExampleCmd.AddCommand(ExampleMyCallCmd)
	ExampleMyCallCmd.PreRun = func(cmd *cobra.Command, args []string) {
		ExampleMyCallCmd.Flags().Parse(args)
		_ExampleMyCallCmdRequest.AddFlags(ExampleMyCallCmd.Flags())
		if ExampleMyCallCmd.Flag("help").Changed {
			ExampleMyCallCmd.Help()
			os.Exit(0)
		}
		_ExampleMyCallCmdRequest.ParseFlags(cmd.Flags(), args)
	}
}

func runExampleMyCallCmd(cmd *cobra.Command, args []string) {
	cmd.Flags().VisitAll(func(f *pflag.Flag) {
		if !f.Changed {
			return
		}
		cli_client.Logger().Info("flag", "name", f.Name, "value", f.Value.String(), "changed", f.Changed)
	})
}

var (
	_ExampleNestedCmdRequest = &NestedRequestFlag{NestedRequest: new(NestedRequest)}
	ExampleNestedCmd         = &cobra.Command{
		Use:                "nested",
		Short:              ``,
		Long:               ``,
		Run:                runExampleNestedCmd,
		FParseErrWhitelist: cobra.FParseErrWhitelist{UnknownFlags: true},
		DisableFlagParsing: true,
	}
)

func init() {
	ExampleCmd.AddCommand(ExampleNestedCmd)
	ExampleNestedCmd.PreRun = func(cmd *cobra.Command, args []string) {
		ExampleNestedCmd.Flags().Parse(args)
		_ExampleNestedCmdRequest.AddFlags(ExampleNestedCmd.Flags())
		if ExampleNestedCmd.Flag("help").Changed {
			ExampleNestedCmd.Help()
			os.Exit(0)
		}
		_ExampleNestedCmdRequest.ParseFlags(cmd.Flags(), args)
	}
}

func runExampleNestedCmd(cmd *cobra.Command, args []string) {
	cmd.Flags().VisitAll(func(f *pflag.Flag) {
		if !f.Changed {
			return
		}
		cli_client.Logger().Info("flag", "name", f.Name, "value", f.Value.String(), "changed", f.Changed)
	})
}

var (
	_ExampleServerSideStreamCmdRequest = &ServerSideStreamRequestFlag{ServerSideStreamRequest: new(ServerSideStreamRequest)}
	ExampleServerSideStreamCmd         = &cobra.Command{
		Use:                "server-side-stream",
		Short:              ``,
		Long:               ``,
		Run:                runExampleServerSideStreamCmd,
		FParseErrWhitelist: cobra.FParseErrWhitelist{UnknownFlags: true},
		DisableFlagParsing: true,
	}
)

func init() {
	ExampleCmd.AddCommand(ExampleServerSideStreamCmd)
	ExampleServerSideStreamCmd.PreRun = func(cmd *cobra.Command, args []string) {
		ExampleServerSideStreamCmd.Flags().Parse(args)
		_ExampleServerSideStreamCmdRequest.AddFlags(ExampleServerSideStreamCmd.Flags())
		if ExampleServerSideStreamCmd.Flag("help").Changed {
			ExampleServerSideStreamCmd.Help()
			os.Exit(0)
		}
		_ExampleServerSideStreamCmdRequest.ParseFlags(cmd.Flags(), args)
	}
}

func runExampleServerSideStreamCmd(cmd *cobra.Command, args []string) {
	cmd.Flags().VisitAll(func(f *pflag.Flag) {
		if !f.Changed {
			return
		}
		cli_client.Logger().Info("flag", "name", f.Name, "value", f.Value.String(), "changed", f.Changed)
	})
}

var (
	_ExampleClientSideStreamCmdRequest = &ClientSideStreamRequestFlag{ClientSideStreamRequest: new(ClientSideStreamRequest)}
	ExampleClientSideStreamCmd         = &cobra.Command{
		Use:                "client-side-stream",
		Short:              ``,
		Long:               ``,
		Run:                runExampleClientSideStreamCmd,
		FParseErrWhitelist: cobra.FParseErrWhitelist{UnknownFlags: true},
		DisableFlagParsing: true,
	}
)

func init() {
	ExampleCmd.AddCommand(ExampleClientSideStreamCmd)
	ExampleClientSideStreamCmd.PreRun = func(cmd *cobra.Command, args []string) {
		ExampleClientSideStreamCmd.Flags().Parse(args)
		_ExampleClientSideStreamCmdRequest.AddFlags(ExampleClientSideStreamCmd.Flags())
		if ExampleClientSideStreamCmd.Flag("help").Changed {
			ExampleClientSideStreamCmd.Help()
			os.Exit(0)
		}
		_ExampleClientSideStreamCmdRequest.ParseFlags(cmd.Flags(), args)
	}
}

func runExampleClientSideStreamCmd(cmd *cobra.Command, args []string) {
	cmd.Flags().VisitAll(func(f *pflag.Flag) {
		if !f.Changed {
			return
		}
		cli_client.Logger().Info("flag", "name", f.Name, "value", f.Value.String(), "changed", f.Changed)
	})
}

var (
	_ExampleBidirectionalStreamCmdRequest = &BidirectionalStreamRequestFlag{BidirectionalStreamRequest: new(BidirectionalStreamRequest)}
	ExampleBidirectionalStreamCmd         = &cobra.Command{
		Use:                "bidirectional-stream",
		Short:              ``,
		Long:               ``,
		Run:                runExampleBidirectionalStreamCmd,
		FParseErrWhitelist: cobra.FParseErrWhitelist{UnknownFlags: true},
		DisableFlagParsing: true,
	}
)

func init() {
	ExampleCmd.AddCommand(ExampleBidirectionalStreamCmd)
	ExampleBidirectionalStreamCmd.PreRun = func(cmd *cobra.Command, args []string) {
		ExampleBidirectionalStreamCmd.Flags().Parse(args)
		_ExampleBidirectionalStreamCmdRequest.AddFlags(ExampleBidirectionalStreamCmd.Flags())
		if ExampleBidirectionalStreamCmd.Flag("help").Changed {
			ExampleBidirectionalStreamCmd.Help()
			os.Exit(0)
		}
		_ExampleBidirectionalStreamCmdRequest.ParseFlags(cmd.Flags(), args)
	}
}

func runExampleBidirectionalStreamCmd(cmd *cobra.Command, args []string) {
	cmd.Flags().VisitAll(func(f *pflag.Flag) {
		if !f.Changed {
			return
		}
		cli_client.Logger().Info("flag", "name", f.Name, "value", f.Value.String(), "changed", f.Changed)
	})
}
