// Code generated by protoc-gen-cli-client. DO NOT EDIT.

package cli

import (
	cli_client "github.com/adlerhurst/cli-client"
	pflag "github.com/spf13/pflag"
	anypb "google.golang.org/protobuf/types/known/anypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

type CallRequestFlag struct {
	*CallRequest

	changed bool
	set     pflag.FlagSet

	UseFieldNameFlag  cli_client.Flag[string]
	UseCustomNameFlag cli_client.StringFlag
	NestedFlag        cli_client.MessageFlag
	RepNestFlag       cli_client.MessageFlag
	CreatedAtFlag     cli_client.MessageFlag
	PayloadFlag       cli_client.MessageFlag
	WatFlag           cli_client.EnumFlag[CallRequest_Wat]
	IsSomethingFlag   cli_client.BoolFlag
	I32Flag           cli_client.Int32Flag
	Ui32Flag          cli_client.Uint32Flag
	I64Flag           cli_client.Int64Flag
	Ui64Flag          cli_client.Uint64Flag
	FlFlag            cli_client.FloatFlag
	DblFlag           cli_client.DoubleFlag
	BeizFlag          cli_client.BytesFlag
	Si32Flag          cli_client.Sint32Flag
	Si64Flag          cli_client.Sint64Flag
	F32Flag           cli_client.Fixed32Flag
	F64Flag           cli_client.Fixed64Flag
	Sf32Flag          cli_client.Sfixed32Flag
	Sf64Flag          cli_client.Sfixed64Flag
	SomeFlag          cli_client.EnumFlag[Some]
	RepSFlag          cli_client.DoubleFlag
	RepWatFlag        cli_client.EnumFlag[CallRequest_Wat]
	SomethingFlag     cli_client.MessageFlag
	OoTextFlag        cli_client.StringFlag
	OoWatFlag         cli_client.EnumFlag[CallRequest_Wat]
	OoNestedFlag      cli_client.MessageFlag
	MetadataFlag      cli_client.MessageFlag
}

type CallRequest_MetadataEntryFlag struct {
	*CallRequest_MetadataEntry

	changed bool
	set     pflag.FlagSet

	KeyFlag   cli_client.StringFlag
	ValueFlag cli_client.BytesFlag
}

type NestedRequest_NestedFlag struct {
	*NestedRequest_Nested

	changed bool
	set     pflag.FlagSet

	IdFlag    cli_client.StringFlag
	DepthFlag cli_client.Int32Flag
}

type ClientSideStreamRequestFlag struct {
	*ClientSideStreamRequest

	changed bool
	set     pflag.FlagSet

	TextFlag cli_client.StringFlag
}

type BidirectionalStreamRequestFlag struct {
	*BidirectionalStreamRequest

	changed bool
	set     pflag.FlagSet

	TextFlag cli_client.StringFlag
}

type CallRequest_NestedFlag struct {
	*CallRequest_Nested

	changed bool
	set     pflag.FlagSet

	FieldFlag cli_client.StringFlag
}

type NestedRequestFlag struct {
	*NestedRequest

	changed bool
	set     pflag.FlagSet

	NestedFlag cli_client.MessageFlag
	IdFlag     cli_client.StringFlag
}

type ServerSideStreamRequestFlag struct {
	*ServerSideStreamRequest

	changed bool
	set     pflag.FlagSet

	TextFlag cli_client.StringFlag
}
