// Code generated by protoc-gen-cli-client. DO NOT EDIT.

package cli

import (
	cli_client "github.com/adlerhurst/cli-client"
	cobra "github.com/spf13/cobra"
	grpc "google.golang.org/grpc"
	os "os"
)

var ExampleCmd = &cobra.Command{
	Use:   "example",
	Short: "This is an example service",
	Long: `This is an example service
The service does nothing
`,
	FParseErrWhitelist: cobra.FParseErrWhitelist{UnknownFlags: true},
	DisableFlagParsing: true,
}

var ExampleCallCmd = &cobra.Command{
	Use:                "call",
	Short:              "",
	Long:               ``,
	FParseErrWhitelist: cobra.FParseErrWhitelist{UnknownFlags: true},
	DisableFlagParsing: true,
}

func init() {
	ExampleCmd.AddCommand(
		ExampleCallCmd,
	)
}

var ExampleCallMyCmd = &cobra.Command{
	Use:   "my",
	Short: "I do absolutely nothing",
	Long: `I do absolutely nothing
because i'm a showcase
`,
	Run:                ExampleCallMyRun,
	FParseErrWhitelist: cobra.FParseErrWhitelist{UnknownFlags: true},
	DisableFlagParsing: true,
}

func init() {
	ExampleCallCmd.AddCommand(
		ExampleCallMyCmd,
	)
}

var ExampleStreamCmd = &cobra.Command{
	Use:                "stream",
	Short:              "",
	Long:               ``,
	FParseErrWhitelist: cobra.FParseErrWhitelist{UnknownFlags: true},
	DisableFlagParsing: true,
}

func init() {
	ExampleCmd.AddCommand(
		ExampleStreamCmd,
	)
}

var ExampleStreamServerCmd = &cobra.Command{
	Use:                "server",
	Short:              "",
	Long:               ``,
	Run:                ExampleStreamServerRun,
	FParseErrWhitelist: cobra.FParseErrWhitelist{UnknownFlags: true},
	DisableFlagParsing: true,
}

func init() {
	ExampleStreamCmd.AddCommand(
		ExampleStreamServerCmd,
	)
}

var ExampleStreamClientCmd = &cobra.Command{
	Use:                "client",
	Short:              "",
	Long:               ``,
	Run:                ExampleStreamClientRun,
	FParseErrWhitelist: cobra.FParseErrWhitelist{UnknownFlags: true},
	DisableFlagParsing: true,
}

func init() {
	ExampleStreamCmd.AddCommand(
		ExampleStreamClientCmd,
	)
}

var ExampleStreamBiDirectionalCmd = &cobra.Command{
	Use:                "bi-directional",
	Short:              "",
	Long:               ``,
	Run:                ExampleStreamBiDirectionalRun,
	FParseErrWhitelist: cobra.FParseErrWhitelist{UnknownFlags: true},
	DisableFlagParsing: true,
}

func init() {
	ExampleStreamCmd.AddCommand(
		ExampleStreamBiDirectionalCmd,
	)
}

var ExampleNestedCmd = &cobra.Command{
	Use:                "nested",
	Short:              "",
	Long:               ``,
	Run:                ExampleNestedRun,
	FParseErrWhitelist: cobra.FParseErrWhitelist{UnknownFlags: true},
	DisableFlagParsing: true,
}

func init() {
	ExampleCmd.AddCommand(
		ExampleNestedCmd,
	)
}

func init() {
	ExampleCallMyCmd.PreRun = func(cmd *cobra.Command, args []string) {
		ExampleCallMyCmd.Flags().Parse(args)
		// TODO: _ClientFilterCmdRequest.AddFlags(ExampleCallMyCmd.Flags())
		if ExampleCallMyCmd.Flag("help").Changed {
			ExampleCallMyCmd.Help()
			os.Exit(0)
		}
		// TODO: _ClientFilterCmdRequest.ParseFlags(cmd.Flags(), args)
	}
}

var (
	ExampleCallMyOptions []grpc.CallOption
	ExampleCallMyRun     = func(cmd *cobra.Command, args []string) {
		conn := cli_client.Connection(cmd.Context())
		defer conn.Close()
		client := NewExampleServiceClient(conn)

		// TODO: set request
		res, err := client.Call(cmd.Context(), nil, ExampleCallMyOptions...)
		if err != nil {
			cli_client.Logger().Error("unable to Call", "cause", err)
			os.Exit(1)
		}
		cli_client.Logger().Info("🎉 request succeeded", "result", res)
	}
)

func init() {
	ExampleNestedCmd.PreRun = func(cmd *cobra.Command, args []string) {
		ExampleNestedCmd.Flags().Parse(args)
		// TODO: _ClientFilterCmdRequest.AddFlags(ExampleNestedCmd.Flags())
		if ExampleNestedCmd.Flag("help").Changed {
			ExampleNestedCmd.Help()
			os.Exit(0)
		}
		// TODO: _ClientFilterCmdRequest.ParseFlags(cmd.Flags(), args)
	}
}

var (
	ExampleNestedOptions []grpc.CallOption
	ExampleNestedRun     = func(cmd *cobra.Command, args []string) {
		conn := cli_client.Connection(cmd.Context())
		defer conn.Close()
		client := NewExampleServiceClient(conn)

		// TODO: set request
		res, err := client.Nested(cmd.Context(), nil, ExampleNestedOptions...)
		if err != nil {
			cli_client.Logger().Error("unable to Nested", "cause", err)
			os.Exit(1)
		}
		cli_client.Logger().Info("🎉 request succeeded", "result", res)
	}
)

func init() {
	ExampleStreamServerCmd.PreRun = func(cmd *cobra.Command, args []string) {
		ExampleStreamServerCmd.Flags().Parse(args)
		// TODO: _ClientFilterCmdRequest.AddFlags(ExampleStreamServerCmd.Flags())
		if ExampleStreamServerCmd.Flag("help").Changed {
			ExampleStreamServerCmd.Help()
			os.Exit(0)
		}
		// TODO: _ClientFilterCmdRequest.ParseFlags(cmd.Flags(), args)
	}
}

var (
	ExampleStreamServerOptions []grpc.CallOption
	ExampleStreamServerRun     = func(cmd *cobra.Command, args []string) {
		conn := cli_client.Connection(cmd.Context())
		defer conn.Close()
		client := NewExampleServiceClient(conn)

		// TODO: set request
		stream, err := client.ServerSideStream(cmd.Context(), nil, ExampleStreamServerOptions...)
		if err != nil {
			cli_client.Logger().Error("unable to ServerSideStream", "cause", err)
			os.Exit(1)
		}
		defer stream.CloseSend()

		res, err := stream.Recv()
		if err != nil {
			cli_client.Logger().Error("unable to receive", "cause", err)
			os.Exit(1)
		}
		cli_client.Logger().Info("🎉 request succeeded", "result", res.String())
	}
)

func init() {
	ExampleStreamClientCmd.PreRun = func(cmd *cobra.Command, args []string) {
		ExampleStreamClientCmd.Flags().Parse(args)
		// TODO: _ClientFilterCmdRequest.AddFlags(ExampleStreamClientCmd.Flags())
		if ExampleStreamClientCmd.Flag("help").Changed {
			ExampleStreamClientCmd.Help()
			os.Exit(0)
		}
		// TODO: _ClientFilterCmdRequest.ParseFlags(cmd.Flags(), args)
	}
}

var (
	ExampleStreamClientOptions []grpc.CallOption
	ExampleStreamClientRun     = func(cmd *cobra.Command, args []string) {
		conn := cli_client.Connection(cmd.Context())
		defer conn.Close()
		client := NewExampleServiceClient(conn)

		stream, err := client.ClientSideStream(cmd.Context(), ExampleStreamClientOptions...)
		if err != nil {
			cli_client.Logger().Error("unable to ClientSideStream", "cause", err)
			os.Exit(1)
		}
		defer stream.CloseSend()
		// TODO: set request
		if err := stream.Send(nil); err != nil {
			cli_client.Logger().Error("unable to send", "cause", err)
			os.Exit(1)
		}

		res, err := stream.CloseAndRecv()
		if err != nil {
			cli_client.Logger().Error("unable to receive and close", "cause", err)
			os.Exit(1)
		}
		cli_client.Logger().Info("🎉 request succeeded", "result", res.String())
	}
)

func init() {
	ExampleStreamBiDirectionalCmd.PreRun = func(cmd *cobra.Command, args []string) {
		ExampleStreamBiDirectionalCmd.Flags().Parse(args)
		// TODO: _ClientFilterCmdRequest.AddFlags(ExampleStreamBiDirectionalCmd.Flags())
		if ExampleStreamBiDirectionalCmd.Flag("help").Changed {
			ExampleStreamBiDirectionalCmd.Help()
			os.Exit(0)
		}
		// TODO: _ClientFilterCmdRequest.ParseFlags(cmd.Flags(), args)
	}
}

var (
	ExampleStreamBiDirectionalOptions []grpc.CallOption
	ExampleStreamBiDirectionalRun     = func(cmd *cobra.Command, args []string) {
		conn := cli_client.Connection(cmd.Context())
		defer conn.Close()
		client := NewExampleServiceClient(conn)

		stream, err := client.BidirectionalStream(cmd.Context(), ExampleStreamBiDirectionalOptions...)
		if err != nil {
			cli_client.Logger().Error("unable to BidirectionalStream", "cause", err)
			os.Exit(1)
		}
		defer stream.CloseSend()

		// TODO: set request
		if err := stream.Send(nil); err != nil {
			cli_client.Logger().Error("unable to send", "cause", err)
			os.Exit(1)
		}

		res, err := stream.Recv()
		if err != nil {
			cli_client.Logger().Error("unable to receive", "cause", err)
			os.Exit(1)
		}
		cli_client.Logger().Info("🎉 request succeeded", "result", res.String())
	}
)
