package v6

import (
	"bytes"
	"log/slog"
	"maps"
	"text/template"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"
	"google.golang.org/protobuf/compiler/protogen"
)

var (
	title = cases.Title(language.English)
	lower = cases.Lower(language.English)
)

func header(gen *protogen.GeneratedFile, file *protogen.File) {
	gen.P("// Code generated by protoc-gen-cli-client. DO NOT EDIT.")
	gen.P()
	gen.P("package ", file.GoPackageName)
	gen.P()
}

var (
	ident = func(path protogen.GoImportPath, name string) protogen.GoIdent {
		return protogen.GoIdent{
			GoName:       name,
			GoImportPath: path,
		}
	}

	qualifier = func(gen *protogen.GeneratedFile) func(ident protogen.GoIdent) string {
		return func(ident protogen.GoIdent) string {
			if ident.GoImportPath == "" {
				return ident.GoName
			}
			return gen.QualifiedGoIdent(ident)
		}
	}

	logger = func(gen *protogen.GeneratedFile) func() string {
		return func() string {
			return qualifier(gen)(protogen.GoIdent{
				GoName:       "Logger()",
				GoImportPath: "github.com/adlerhurst/cli-client",
			})
		}
	}
)

func generate(gen *protogen.GeneratedFile, name, tmpl string, data any, additionalFuncs template.FuncMap) error {
	var buffer bytes.Buffer

	maps.Copy(additionalFuncs, template.FuncMap{
		"ident":   ident,
		"qualify": qualifier(gen),
		"logger":  logger(gen),
		"gen":     func() *protogen.GeneratedFile { return gen },
	})

	err := template.Must(template.New(name).
		Funcs(additionalFuncs).
		Parse(tmpl)).
		Execute(&buffer, data)

	if err != nil {
		slog.Error("failed to execute template", "cause", err)
		return err
	}

	_, err = gen.Write(buffer.Bytes())
	if err != nil {
		slog.Error("failed to write", "cause", err)
	}

	return err
}
