// Code generated by protoc-gen-cli-client. DO NOT EDIT.

package cli

import (
	cobra "github.com/spf13/cobra"
)

func (msg *NestedRequest) Flags(cmd *cobra.Command) error {}

func (msg *NestedResponse) Flags(cmd *cobra.Command) error {}

func (msg *CallRequest) Flags(cmd *cobra.Command) error {}

func (msg *CallResponse) Flags(cmd *cobra.Command) error {}

func (msg *ServerSideStreamRequest) Flags(cmd *cobra.Command) error {}

func (msg *ServerSideStreamResponse) Flags(cmd *cobra.Command) error {}

func (msg *ClientSideStreamRequest) Flags(cmd *cobra.Command) error {}

func (msg *ClientSideStreamResponse) Flags(cmd *cobra.Command) error {}

func (msg *BidirectionalStreamRequest) Flags(cmd *cobra.Command) error {}

func (msg *BidirectionalStreamResponse) Flags(cmd *cobra.Command) error {}
