// Code generated by protoc-gen-cli-client. DO NOT EDIT.

package cli

import (
	cobra "github.com/spf13/cobra"
)

var ExampleServiceCommand = &cobra.Command{
	Use:   "example-service",
	Short: "This is an example service",
	Long: `This is an example service
The service does nothing`,
}

func init() {
	ExampleServiceCommand.AddCommand(ExampleServiceCallCommand)
}

var ExampleServiceCallCommand = &cobra.Command{
	Use:   "call",
	Short: "I do absolutely nothing",
	Long: `I do absolutely nothing
because i'm a showcase`,
}

func init() {
	ExampleServiceCommand.AddCommand(ExampleServiceNestedCommand)
}

var ExampleServiceNestedCommand = &cobra.Command{
	Use:   "nested",
	Short: "",
	Long:  ``,
}

func init() {
	ExampleServiceCommand.AddCommand(ExampleServiceServerSideStreamCommand)
}

var ExampleServiceServerSideStreamCommand = &cobra.Command{
	Use:   "server-side-stream",
	Short: "",
	Long:  ``,
}

func init() {
	ExampleServiceCommand.AddCommand(ExampleServiceClientSideStreamCommand)
}

var ExampleServiceClientSideStreamCommand = &cobra.Command{
	Use:   "client-side-stream",
	Short: "",
	Long:  ``,
}

func init() {
	ExampleServiceCommand.AddCommand(ExampleServiceBidirectionalStreamCommand)
}

var ExampleServiceBidirectionalStreamCommand = &cobra.Command{
	Use:   "bidirectional-stream",
	Short: "",
	Long:  ``,
}
