// Code generated by protoc-gen-cli-client. DO NOT EDIT.

package cli

// import (
// 	cli_client "github.com/adlerhurst/cli-client"
// 	pflag "github.com/spf13/pflag"
// 	anypb "google.golang.org/protobuf/types/known/anypb"
// 	structpb "google.golang.org/protobuf/types/known/structpb"
// 	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
// )

// type NestedRequestFlag struct {
// 	set pflag.FlagSet

// 	_Id     cli_client.Flag[string]
// 	_Nested cli_client.Flag[*NestedRequest_Nested]
// }

// func (x *NestedRequestFlag) Value() *NestedRequest {
// 	return &NestedRequest{}
// }

// type NestedResponseFlag struct {
// 	set pflag.FlagSet
// }

// func (x *NestedResponseFlag) Value() *NestedResponse {
// 	return &NestedResponse{}
// }

// type CallRequestFlag struct {
// 	set pflag.FlagSet

// 	_Beiz          cli_client.Flag[[]byte]
// 	_CreatedAt     cli_client.Flag[*timestamppb.Timestamp]
// 	_Dbl           cli_client.Flag[float64]
// 	_F32           cli_client.Flag[uint32]
// 	_F64           cli_client.Flag[uint64]
// 	_Fl            cli_client.Flag[float32]
// 	_I32           cli_client.Flag[*int32]
// 	_I64           cli_client.Flag[int64]
// 	_IsSomething   cli_client.Flag[bool]
// 	_Metadata      cli_client.Flag[*CallRequest_MetadataEntry]
// 	_Nested        cli_client.Flag[*CallRequest_Nested]
// 	_OoNested      cli_client.Flag[*CallRequest_Nested]
// 	_OoText        cli_client.Flag[string]
// 	_OoWat         cli_client.Flag[CallRequest_Wat]
// 	_Payload       cli_client.Flag[*structpb.Struct]
// 	_RepNest       cli_client.SliceFlag[*CallRequest_Nested]
// 	_RepS          cli_client.SliceFlag[float64]
// 	_RepWat        cli_client.SliceFlag[CallRequest_Wat]
// 	_Sf32          cli_client.Flag[int32]
// 	_Sf64          cli_client.Flag[int64]
// 	_Si32          cli_client.Flag[int32]
// 	_Si64          cli_client.Flag[int64]
// 	_Some          cli_client.Flag[Some]
// 	_Something     cli_client.Flag[*anypb.Any]
// 	_Ui32          cli_client.Flag[uint32]
// 	_Ui64          cli_client.Flag[uint64]
// 	_UseCustomName cli_client.Flag[string]
// 	_UseFieldName  cli_client.Flag[string]
// 	_Wat           cli_client.Flag[CallRequest_Wat]
// }

// func (x *CallRequestFlag) Value() *CallRequest {
// 	return &CallRequest{}
// }

// type CallResponseFlag struct {
// 	set pflag.FlagSet

// 	_Number cli_client.Flag[int64]
// }

// func (x *CallResponseFlag) Value() *CallResponse {
// 	return &CallResponse{}
// }

// type ServerSideStreamRequestFlag struct {
// 	set pflag.FlagSet

// 	_Text cli_client.Flag[string]
// }

// func (x *ServerSideStreamRequestFlag) Value() *ServerSideStreamRequest {
// 	return &ServerSideStreamRequest{}
// }

// type ServerSideStreamResponseFlag struct {
// 	set pflag.FlagSet

// 	_Number cli_client.Flag[int64]
// }

// func (x *ServerSideStreamResponseFlag) Value() *ServerSideStreamResponse {
// 	return &ServerSideStreamResponse{}
// }

// type ClientSideStreamRequestFlag struct {
// 	set pflag.FlagSet

// 	_Text cli_client.Flag[string]
// }

// func (x *ClientSideStreamRequestFlag) Value() *ClientSideStreamRequest {
// 	return &ClientSideStreamRequest{}
// }

// type ClientSideStreamResponseFlag struct {
// 	set pflag.FlagSet

// 	_Number cli_client.Flag[int64]
// }

// func (x *ClientSideStreamResponseFlag) Value() *ClientSideStreamResponse {
// 	return &ClientSideStreamResponse{}
// }

// type BidirectionalStreamRequestFlag struct {
// 	set pflag.FlagSet

// 	_Text cli_client.Flag[string]
// }

// func (x *BidirectionalStreamRequestFlag) Value() *BidirectionalStreamRequest {
// 	return &BidirectionalStreamRequest{}
// }

// type BidirectionalStreamResponseFlag struct {
// 	set pflag.FlagSet

// 	_Number cli_client.Flag[int64]
// }

// func (x *BidirectionalStreamResponseFlag) Value() *BidirectionalStreamResponse {
// 	return &BidirectionalStreamResponse{}
// }
